// react-ajax-router/src/App.js
import React from "react";
import { Link, BrowserRouter as Router } from "react-router-dom";
import Routes from "./routes/index.js";

function App() {
  return (
    <Router>
      <header>
        <Link to="/">
          <button>Home</button>
        </Link>
        <Link to="/about">
          <button>About</button>
        </Link>
        <Link to="/imageList">
          <button>GIF 검색</button>
        </Link>
        <Link to="/users">
          <button>Users</button>
        </Link>
      </header>
      <hr />
      <main>
        <Routes />
      </main>
    </Router>
  );
}

export default App;

// svelte-ajax-router/src/App.svelte
<script>
	import { Link } from 'yrv'
	import Routes from './routes/index.svelte'
</script>

<ul class="navigation-links">
	<li><Link href="/" className="btn">Home</Link></li>
	<li><Link href="#!/about" className="btn">About</Link></li>
	<li><Link href="#!/imageList" className="btn">GIF 검색</Link></li>
	<li><Link href="#!/users" className="btn">Users</Link></li>
</ul>

<Routes />
