// vue-cli-ajax-router/src/App.vue
<template>
  <div>
    <router-link to="/" exact>Home</router-link>
    <router-link to="/about" exact>About</router-link>
    <router-link to="/imageList" exact>GIF 검색</router-link>
    <router-link to="/users" exact>Users</router-link>
    <router-view></router-view>
  </div>
</template>

<script>

export default {
  name: 'app',
}
</script>

<style>
#app {
  text-align: center;
}
</style>

// react-ajax-router/src/App.js
import React from "react";
import { Link, BrowserRouter as Router } from "react-router-dom";
import Routes from "./routes/index.js";

function App() {
  return (
    <Router>
      <header>
        <Link to="/">
          <button>Home</button>
        </Link>
        <Link to="/about">
          <button>About</button>
        </Link>
        <Link to="/imageList">
          <button>GIF 검색</button>
        </Link>
        <Link to="/users">
          <button>Users</button>
        </Link>
      </header>
      <hr />
      <main>
        <Routes />
      </main>
    </Router>
  );
}

export default App;
