// vue-cli-ajax-router/src/pages/gif-finder/FetchList.vue
<template>
<div>
    <div v-if="!images">loading...</div>
    <details v-else v-for="image in images" v-bind:key="image.id">
        <summary>{{image.type}}</summary>
        <strong>{{image.id}}</strong> years old
        <br />
        lives in {{image.url}}
    </details>
</div>
</template>

<script>
export default {
  name: "ImageList",
  data() {
    return {
      images: null
    };
  },
  beforeMount() {
    this.fetchImagesData();
  },
  methods: {
    async fetchImagesData() {
      const res = await fetch(new Request("https://api.giphy.com/v1/gifs/search?api_key=3eFQvabDx69SMoOemSPiYfh9FY0nzO9x&q=cat&offset=0&limit=3" ));
      const { data } = await res.json();
      this.images = data;

    }
  }
};
</script>

// react-ajax-router/src/pages/gif-finder/FetchList.js
import React, { useState, useEffect } from "react";

export default function ImageList() {
  const [images, setImages] = useState(null);

  async function fetchImagesData(id) {
    const response = await fetch("https://api.giphy.com/v1/gifs/search?api_key=3eFQvabDx69SMoOemSPiYfh9FY0nzO9x&q=cat&offset=0&limit=3");
    setImages( await response.json());
  }

  useEffect(() => {
    fetchImagesData();
  });

  if (!images) {
    return "loading...";
  }else{
    return (
      <>
        {images.data.map((image, i) => {
            return (<Image image={image} key={i}/>);
        })}
      </>
    );
  }
}

function Image(prop) {
  return (
      <details>
        <summary>{prop.image.type}</summary>
        <strong>{prop.image.id}</strong> years old
        <br />
        lives in {prop.image.url}
    </details>
  );
}
