// react-ajax-router/src/routes/index.js
import React from "react";
import { Route, Switch } from "react-router-dom";
import Home from "../pages/main/Home";
import About from "../pages/main/About";
import ImageList from "../pages/gif-finder/FetchList";
import NotFound from "../pages/exception/NotFound";

function Routes() {
  return (
    <Switch>
      <Route exact path="/" component={Home} />
      <Route path="/about" component={About} />
      <Route path="/imageList" component={ImageList} />
      <Route component={NotFound} />
    </Switch>
  );
}

export default Routes;

// svelte-dashboard/src/routes/index.svelte
<script>
	import { Router, Route } from 'yrv'
	import Home from '../pages/main/Home.svelte'
	import About from '../pages/main/About.svelte'
	import NotFound from '../pages/exception/NotFound.svelte'
</script>

<Router>
	<Route exact path="/" redirect="/#!" />
	<Route exact path="#!" component={Home} />
	<Route exact path="#!/about" component={About} />
	<Route fallback component={NotFound} />
</Router>
