// react-example/src/App.js
import React from "react";
import { Link, Route, Switch, HashRouter as Router } from "react-router-dom";
import Home from "./pages/main/Home";
import About from "./pages/main/About";
import NotFound from "./pages/exception/NotFound";

function App() {
  return (
    <Router>
      <header>
        <Link to="/">
          <button>Home</button>
        </Link>
        <Link to="/about">
          <button>About</button>
        </Link>
        <Link to="/users">
          <button>Users</button>
        </Link>
      </header>
      <hr />
      <main>
        <Switch>
          <Route exact path="/" component={Home} />
          <Route path="/about" component={About} />
          <Route component={NotFound} />
        </Switch>
      </main>
    </Router>
  );
}

export default App;

// vue-cli-example/src/App.vue
<template>
  <div>
    <router-link to="/" exact>Home</router-link>
    <router-link to="/about" exact>About</router-link>
    <router-link to="/users" exact>Users</router-link>
    <router-view></router-view>
  </div>
</template>

<script>

export default {
  name: 'app',
}
</script>

<style>
#app {
  text-align: center;
}
</style>
